context:
  version: "2.0.0"

package:
  name: msedit
  version: ${{ version }}

source:
  url: https://github.com/microsoft/edit/archive/v${{ version }}.tar.gz
  sha256: f35da309c5f3d92b10e5c4b2267e4d5e29d809b2aa460e80326b11f7feba72a5

build:
  number: 1
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
      RUSTC_BOOTSTRAP: 1
      EDIT_CFG_LANGUAGES: en,zh_hans
    content:
      - if: unix
        then:
          - cargo auditable install -j ${CPU_COUNT} --root "${PREFIX}" --path crates/edit --locked --no-track
        else:
          - cargo auditable install -j %CPU_COUNT% --root "%PREFIX%" --path crates/edit --locked --no-track
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - rust-src

tests:
  - script:
      - edit --help
      - edit --version

about:
  homepage: https://github.com/microsoft/edit
  summary: "A simple editor for simple needs."
  description: |
    This editor pays homage to the classic MS-DOS Editor, but with a modern interface and input controls similar to VS Code. The goal is to provide an accessible editor that even users largely unfamiliar with terminals can easily use.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/microsoft/edit

extra:
  recipe-maintainers:
    - XhstormR
